# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Release

on:
  release:
    types: [published]

env:
  DOTNET_VERSION: 6.0.x
  PROJECT_PATH: FSBLib/FSBLib.csproj
  CONFIGURATION: Release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
    
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Test
      run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal
    
    - name: Pack NuGet
      run: dotnet pack ${{ env.PROJECT_PATH }} --configuration ${{ env.CONFIGURATION }} --no-build --output nupkgs
    
    - name: Upload NuGet Package to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          nupkgs/*.nupkg
          FSBLib/bin/${{ env.CONFIGURATION }}/netstandard2.0/FSBLib.dll
          FSBLib/bin/${{ env.CONFIGURATION }}/netstandard2.0/FSBLib.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish NuGet Package to NuGet.org
      run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
